import Head from 'next/head'
import { Button, Table } from 'react-bootstrap'
import styles from '../styles/Home.module.css'
import React,{useState, useEffect} from 'react';
import axios from 'axios';
import {useRouter} from 'next/router'

export default function Home() {
  const [todos, setTodos] = useState([]);
  const router = useRouter();

  const getTodo = async() => {
    const result = await axios.get('/api/todo');
    console.log(result);
    setTodos(result.data.users);
  }

  const editTodo = (todo) => {
    console.log(todo)
    router.push({pathname:'/updateTodo',query:todo});
  }

  const deleteTodo = async(todo) => {
    const result = await axios.delete(`/api/todo/${todo._id}`);
    alert(result.data);
    getTodo();
  }


  useEffect(()=>{
    getTodo();
  },[]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button href='/Addtodo' className='m-4'>Add Todo</Button>

      <Table striped bordered hover variant="dark">
        <thead>
          <tr>
            <th>Sl. no</th>
            <th>Title</th>
            <th>Description</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {todos.map((todo, ind) => {
            return (
              <tr key={todo._id}>
                <td>{ind + 1}</td>
                <td>{todo.title}</td>
                <td>{todo.description}</td>
                <td><Button variant='info' onClick={() => editTodo(todo)}>Edit</Button> &nbsp; / &nbsp;
                <Button variant='danger' onClick={() => deleteTodo(todo)}>Delete</Button></td>
              </tr>
            )
          })
            
          }
        </tbody>
      </Table>

    </div>
  )
}
